runtime: php
env: flex

runtime_config:
  document_root: public

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 0.5
  memory_gb: 2.5
  disk_size_gb: 10
